baseURL = "https://storj.io/"
languageCode = "en-us"
title = "storj.io"

[permalinks]
  404 = "/404/"
  community = "/community/"
  partners = "/partners/"
  privacy-policy = "/privacy-policy/"
  terms-of-use = "/terms-of-use/"
  code-of-conduct = "/code-of-conduct/"
  information-policy = "/information-policy/"
  canary = "/canary/"
  whitepaper = "/whitepaper/"
  team = "/team/"
  careers = "/careers/"
  press = "/press/"
  press-kit = "/press-kit/"
  open-source = "/open-source/"
  storage-node-operator="/storage-node-operator/"
  sign-up-node-operator-form = "/sign-up-node-operator/"
  sign-up-node-operator-email = "/sign-up-node-operator-email/"
  sign-up-node-operator-complete = "/sign-up-node-operator-complete/"
  storj-share-information = "/storj-share-information/"
  community-reporting = "/community-reporting/"
  storj-operator-terms = "/storj-operator-terms/"
  spanish-invite = "/spanish-invite/"
  german-invite = "/german-invite/"
  russian-invite = "/russian-invite/"
  mandarin-invite = "/mandarin-invite/"
  sign-up-success = "/sign-up-success/"
  thankyou = "/thankyou/"
	unsubscribed-newsletters = "/unsubscribed-newsletters/"
	unsubscribed-notifications = "/unsubscribed-notifications/"
	unsubscribed-offline-notifications = "/unsubscribed-offline-notifications/"
	dei="/dei"
